# Generated by Django 3.0.6 on 2020-08-10 23:08

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curriculum', models.FileField(blank=True, null=True, upload_to='curriculums/')),
            ],
        ),
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['order', 'title'], 'verbose_name': 'Empleo', 'verbose_name_plural': 'Empleos'},
        ),
        migrations.AlterField(
            model_name='page',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='Descripción del empleo'),
        ),
        migrations.AlterField(
            model_name='page',
            name='order',
            field=models.SmallIntegerField(default=0, verbose_name='Orden de publicación'),
        ),
        migrations.AlterField(
            model_name='page',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Nombre del empleo'),
        ),
    ]
