# Generated by Django 3.0.6 on 2020-08-10 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_auto_20200809_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='tipo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
